// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func NavbarDashboard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex p-4\"><div class=\"hidden md:flex items-center rounded-full ring-[1.5px] gap-2 text-xs ring-gray-300 px-2\"><img src=\"/static/images/search.png\" width=\"14\" height=\"14\" class=\"\"> <input type=\"text\" placeholder=\"Search...\" class=\"w-[200px] p-1 bg-transparent outline-none\"></div><div class=\"flex w-full justify-end items-center gap-4\"><div class=\"flex bg-white rounded-full items-center justify-center h-7 w-7 cursor-pointer shadow-md\"><img src=\"/static/images/message.png\" width=\"20\" height=\"20\"></div><div class=\"relative flex bg-white rounded-full items-center justify-center h-7 w-7 cursor-pointer shadow-md\"><img src=\"/static/images/announcement.png\" width=\"20\" height=\"20\"><div class=\"absolute rounded-full -top-3 -right-3 flex justify-center text-center bg-purple-500 text-white h-5 w-5\">12</div></div><div class=\"flex flex-col\"><span class=\"text-xs leading-3 font-medium\">Ananto Wicaksono</span> <span class=\"text-[10px] text-gray-500 text-right\">Admin</span></div><img src=\"/static/images/avatar.png\" width=\"36\" height=\"36\" class=\"rounded-full\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
